### ISSUE TITLE
Manually package MangoHUD

### ISSUE THREAD

**Issue by Sterophonick** [flathub/org.prismlauncher.PrismLauncher#13]
It'd be nice to have MangoHUD packaged with this flatpak, to allow for limiting the framerate with legacy versions of Minecraft that lack VSync support to conserve battery life on the Steam Deck.

**Comment by orowith2os** [comment]
There's already a Flatpak extension available, there's no need to bundle it.

**Comment by Scrumplex** [comment]
The recommended way is to install the flatpak extension:

```
flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud
```

Make sure to select the 22.08 branch
