### ISSUE TITLE
Use of unpatched zlib 1.2.12 in 22.08 runtime causes `java.util.zip.ZipException: invalid entry CRC` on at least some platforms

### ISSUE THREAD

**Issue by Ryex** [flathub/org.prismlauncher.PrismLauncher#15]
The freedektop SDK behind the org.KDE.Platform runtime version 22.08 uses an unpatched zlib 1.2.12 and leads to the experiencing of  https://github.com/madler/zlib/issues/613 on at least some platforms

the version of zlib should be patched or updated to 1.2.13 or the runtime should be updated to alleviate this issue.

**Comment by DioEgizio** [comment]
Interesting. I do remember that bug when it first was noticed, basically all arch users couldn't play Minecraft lol. But weird that the sdk isn't updated

**Comment by Ryex** [comment]
yeah, its weird. it happens on my laptop but not my desktop.

**Comment by InfiniteLoopGameDev** [comment]
I have a friend that is having this exact issue

**Comment by orowith2os** [comment]
Fixed in https://github.com/flathub/org.prismlauncher.PrismLauncher/pull/18

**Comment by Ryex** [comment]
#18 fixes it for me
