### ISSUE TITLE
Arm 32 bit support

### ISSUE THREAD

**Issue by pandaninjas** [flathub/org.prismlauncher.PrismLauncher#24]
Is there any plan for 32 bit arm support through flatpak? 

I'm trying to test the performance of Minecraft on resource constrained hardware such as a Raspberry Pi

**Comment by guihkx** [comment]
There's no Freedesktop runtime for armv7 [anymore](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1105), so this won't be possible.
