### ISSUE TITLE
java 9 is java 17 ?

### ISSUE THREAD

**Issue by Commandcracker** [flathub/org.prismlauncher.PrismLauncher#29]
I'm running a clean fedora 38 install. I created a instance with minecraft 1.8.9 and changed the java installation to java 8. When i run the instance I get this error message:
```
This instance is not compatible with Java version 17.
Please switch to one of the following Java versions for this instance:
Java version 8
Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing.
```

![Screenshot_20230704_232943](https://github.com/flathub/org.prismlauncher.PrismLauncher/assets/49335821/b7e7d2b3-f92e-4ab9-b5fd-8821b07a560a)
![Screenshot_20230704_232958](https://github.com/flathub/org.prismlauncher.PrismLauncher/assets/49335821/f1f54e7e-9314-4706-ae2b-4320184bec2e)

It says java 8 but then java 17 ??
![Screenshot_20230704_233155](https://github.com/flathub/org.prismlauncher.PrismLauncher/assets/49335821/a0ceea2a-2292-4753-9966-9fee1f8605d7)

Full Minecraft log: https://mclo.gs/cuu9uVj

**Comment by guihkx** [comment]
Enable this option:

![image](https://github.com/flathub/org.prismlauncher.PrismLauncher/assets/626206/9150c538-ea62-47c5-b8fe-3e058388c712)

**Comment by Commandcracker** [comment]
I tried, but it will make my Minecraft look like this
![image](https://github.com/flathub/org.prismlauncher.PrismLauncher/assets/49335821/321e2c26-52cd-4d5f-9212-3904467b8245)

**Comment by Commandcracker** [comment]
The log for that: https://mclo.gs/9xEYMH9
```
[23:52:17] [Client thread/ERROR]: ########## GL ERROR ##########
[23:52:17] [Client thread/ERROR]: @ Pre render
[23:52:17] [Client thread/ERROR]: 1281: Invalid value
```

**Comment by Commandcracker** [comment]
I tried it on my laptop same config, clean fedora 38 and I had no issues.

Conclusion: Fuck NVIDIA

**Comment by guihkx** [comment]
Yeah, I suspect that's unrelated to the original issue, because it works here (also an NVIDIA GPU, but much older video drivers):

![image](https://github.com/flathub/org.prismlauncher.PrismLauncher/assets/626206/de0368ec-f7d3-4c7d-a1a3-c2a045222d5a)

Perhaps you could try a previous version of the driver or something.

**Comment by Commandcracker** [comment]
I installed prismlauncher with dnf and i got the same issue ._.

**Comment by guihkx** [comment]
Are you using some kind of graphic-enhancing mods (e.g. OptiFine)?

If you are, try disabling them. Otherwise, try using a previous version of NVIDIA drivers (e.g. 525.125.06).

**Comment by Commandcracker** [comment]
> Are you using some kind of graphic-enhancing mods (e.g. OptiFine)?

No

I have tried it with the official minecraft launcher, same issue.

> Otherwise, try using a previous version of NVIDIA drivers (e.g. 525.125.06).
i'll do that :)

I'll also close the issue now because it is not Prism or Flatpack related!
I will tinker a bit with my system conf and ill add the solution to this issue, when i find one, so other people who might find this issue have it easier to fix it.
