### ISSUE TITLE
Update runtime to org.kde.Platform//6.*

### ISSUE THREAD

**Issue by devurandom** [flathub/org.prismlauncher.PrismLauncher#53]
`org.prismlauncher.PrismLauncher` currently builds against `org.kde.Platform//5.15-23.08` (cf. https://github.com/flathub/org.prismlauncher.PrismLauncher/blob/ff1b20d42dc5add9239d94a31a00dfe62235580a/org.prismlauncher.PrismLauncher.yml#L2-L3) while `org.kde.Platform//6.5` and `org.kde.Platform//6.6` are already available.

**Comment by Scrumplex** [comment]
We currently have the beta branch for this (accessible through Flathub Beta)

We will definitely switch to 6.6 on the main branch at some currently undetermined time
