### ISSUE TITLE
Flathub 404 page

### ISSUE THREAD

**Issue by Kingproone** [flathub/org.prismlauncher.PrismLauncher#55]
So I don't know if this is the right place for this issue or the main repo, but the application page on
https://flathub.org/apps/org.prismlauncher.PrismLauncher gives a 404

**Comment by Scrumplex** [comment]
That's odd. Let me ask flathub staff

**Comment by Scrumplex** [comment]
This doesn't seem to affect flatpak clients (`flatpak search prismlauncher` still yields this flatpak) so people should still be able to install/update Prism Launcher

**Comment by Kingproone** [comment]
That's nice, still odd that the page went down.

**Comment by TheKodeToad** [comment]
You can still access it at https://flathub.org/en-GB/apps/org.prismlauncher.PrismLauncher
I wonder if this is some kind of bug with the website

**Comment by Scrumplex** [comment]
It is back on the main page for me
