### ISSUE TITLE
Java Large Pages do not work in flatpak

### ISSUE THREAD

**Issue by SusStew** [flathub/org.prismlauncher.PrismLauncher#61]
Using these two Java options `-XX:+UseLargePages -XX:+UseTransparentHugePages` in the flatpak version of Prism Launcher says that Large/Huge pages are not supported. When using the exact same options in the appimage version, they work.

**Comment by Scrumplex** [comment]
See #60

**Comment by SusStew** [comment]
I didn't even notice that there was a pull request that was posted only a week ago! What a coincidence! Anyway, thanks for merging it

**Comment by lordofpipes** [comment]
> I didn't even notice that there was a pull request that was posted only a week ago! What a coincidence!

Yes! I had been wondering for a while why THP didn't work in the Flatpak but only recently took the plunge to diagnose the problem.
