### ISSUE TITLE
Update the runtime

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.prismlauncher.PrismLauncher#83]
Please consider updating the runtime used by this Flatpak to `6.8`. The currently used 6.7 runtime is still based on the 23.08 fd runtime.

**Comment by amlib** [comment]
After upgrading to the new version with this change launching minecraft wraped with gamescope ceased to work. Only reverting to the previous version fixed it. PrismLauncher can't find gamescope executable anymore.

I'm using the gamescope as provided from org.freedesktop.Platform.VulkanLayer.gamescope. I have both 23.08 and 24.08 branches installed.
